name: ci 
on:
  push:
    branches:
      - master 
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.x
      # - uses: actions/cache@v2
      #   with:
      #     key: ${{ github.ref }}
      #     path: .cache
      # - run: pip install mkdocs-material
      # - run: pip install pillow cairosvg
      # - run: mkdocs gh-deploy --force
      
      - name: Docker login
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: 
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v1
        with:
          images: migupele/java_school_online_store_documentation
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
